# Generated by Django 2.2 on 2020-12-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_movie_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='day',
            field=models.IntegerField(null=True),
        ),
    ]
